javac Random1.java
javac PuzzlePosition.java
javac PuzzleEvent.java
javac PositionEvent.java
javac MessageEvent.java
javac DisplayEvent.java
javac PuzzleListener.java
javac SolutionEvent.java
javac SolutionListener.java
javac PuzzleData.java
javac PuzzleMove.java
javac PuzzleSolution.java
javac AutoData.java
javac SolveTilePuzzle.java
javac PuzzleDisplay.java
javac AutoDisplay.java
javac WindowCloseAdapter.java
javac PuzzleDrawnAdapter.java
javac PuzzleDrawnDisplay.java
javac PuzzleImageDisplay.java
javac PuzzleButtonDisplay.java
javac ThumbnailImage.java
javac InformationPanel.java
javac RegularControls.java
javac ResizeControls.java
javac FilePreviewer.java
javac StyleControls.java
javac SpeedControls.java
javac TilePuzzle.java
